### ISSUE TITLE
No touchpad

### ISSUE THREAD

**Issue by danilo-jlle** [Jookia/elan_i2c_dkms#1]
Hi.
I have an Ideapad 330S-15ARR with Manjaro.
I'm not able to use my touchpad despite the elan_i2c_dkms.
I've tested on both 4.19.42-1 and 4.20.17-1 kernels.
Checking dmesg I've found:
[   10.190995] i2c_hid i2c-ELAN469D:00: i2c-ELAN469D:00 supply vdd not found, using dummy regulator
[   10.191023] i2c_hid i2c-ELAN469D:00: Linked as a consumer to regulator.0
[   10.191025] i2c_hid i2c-ELAN469D:00: i2c-ELAN469D:00 supply vddl not found, using dummy regulator
Do you have any tips?

**Comment by Jookia** [comment]
@danilo-jlle it looks like @pavlepiramida fixed this at https://github.com/pavlepiramida/elan_i2c_dkms

**Comment by pavlepiramida** [comment]
@danilo-jlle 
check this out,
should be a straight forward fix

https://wiki.archlinux.org/index.php/libinput#Touchpad_not_detected_at_all

@Jookia thats just a forky-fork of your work,Ive just added support for S145

**Comment by danilo-jlle** [comment]
Hi.
Thanks for the tips.
It turns out that I was able to "fix" the issue some time ago by replacing "noapic" (needed to fix a black screen boot issue) with "ivrs_ioapic[32]=00:14.0" at GRUB kernel parameters, as described here: https://forum.manjaro.org/t/lenovo-ideapad-330s-15arr-no-touchpad/88130/34

I think we can close this topic.

Thank you.

**Comment by Jookia** [comment]
Alright, closey closed.
